# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "weather-watcher-webapp/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - restore_cache:
          keys:
          - yarn-cache

      - run:
          working_directory: ~/repo/weather-watcher-webapp
          command: yarn install

      - save_cache:
          paths:
            - ~/.yarn-cache
          key: yarn-cache

      # run tests!
      - run:
          working_directory: ~/repo/weather-watcher-webapp
          command: yarn test

      - store_test_results:
          path: ~/repo/weather-watcher-webapp/reports

      - deploy:
          working_directory: ~/repo/weather-watcher-webapp
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn run deploy:prod-ci
            fi
