export const CREATE_COMPARISON = 'app/Database/CREATE_COMPARISON';
export const ADD_COMPARISON_POINT = 'app/Database/ADD_COMPARISON_POINT';
export const REMOVE_COMPARISON_POINT = 'app/Database/REMOVE_COMPARISON_POINT';
